#!/usr/bin/with-contenv bash 

echo "**** adding plex-tubearchivist deps to package install list ****"

if [ -f /sbin/apk ]; then
  # Alpine
  echo "\
    git \
    python3 \
    py3-pip" >> /mod-repo-packages-to-install.list
else
  ## Ubuntu
  echo "\
    git \
    python3 \
    python3-pip" >> /mod-repo-packages-to-install.list
fi
   
echo "\
    urllib" >> /mod-pip-packages-to-install.list
