#!/usr/bin/with-contenv bash 

echo "**** adding plex-tubearchivist deps to package install list ****"

if [ -z `command -v git` ]; then
  if [ -f /sbin/apk ]; then
    # Alpine
    echo "\
      git" >> /mod-repo-packages-to-install.list
  else
    ## Ubuntu/others
    echo "\
      git" >> /mod-repo-packages-to-install.list
  fi
else
  echo "**** plex-tubearchivist deps already installed, skipping ****"
fi
